workspace:
  base: /drone
  path: src

branches: [master, stable10, stable9.1, stable9]

clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false
      event: [push, pull_request]

  composer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ./tests/drone/composer-install.sh
    when:
      event: [push, pull_request]

  yarn:
    image: owncloudci/nodejs:latest
    pull: true
    commands:
      - ./tests/drone/yarn-install.sh
    when:
      event: [push, pull_request]

  rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - lib/composer
      - core/vendor
      - build/node_modules
    when:
      local: false
      event: [ push ]

  flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [push]

  phpunit:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    group: test
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - DB_TYPE=${DB_TYPE}
      - ENABLE_COVERAGE=${ENABLE_COVERAGE}
    commands:
      - ./tests/drone/test-phpunit.sh
    when:
      event: [push, pull_request]
      matrix:
        TEST_SUITE: phpunit

  javascript:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    group: test
    commands:
      - ./tests/drone/test-javascript.sh
    when:
      matrix:
        TEST_SUITE: phpunit

  codecov:
    image: plugins/codecov:1
    secrets: [codecov_token]
    pull: true
    files:
     - tests/autotest-clover-${DB_TYPE}.xml
     - tests/autotest-external-clover-${DB_TYPE}.xml
    when:
      event: [push, pull_request]
      matrix:
        TEST_SUITE: phpunit
        ENABLE_COVERAGE: true

services:
  mariadb:
    image: mariadb:10.2
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mariadb

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  mysqlmb4:
    image: mysql:5.7
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysqlmb4

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=owncloud
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=owncloud
    when:
      matrix:
        DB_TYPE: postgres

  owncloud_external:
    image: owncloud/server:latest
    when:
      matrix:
        FILES_EXTERNAL_TYPE: Webdav

  oracle:
    image: deepdiver/docker-oracle-xe-11g
    environment:
       - ORACLE_USER=system
       - ORACLE_PASSWORD=oracle
       - ORACLE_DB=owncloud
    when:
      matrix:
        DB_TYPE: oracle

matrix:
  include:
    # PHP 5.6
    #- PHP_VERSION: 5.6
    #  DB_TYPE: sqlite
    #  TEST_SUITE: phpunit
    #- PHP_VERSION: 5.6
    #  DB_TYPE: mariadb
    #  TEST_SUITE: phpunit
    #- PHP_VERSION: 5.6
    #  DB_TYPE: mysql
    #  TEST_SUITE: phpunit
    - PHP_VERSION: 5.6
      DB_TYPE: postgres
      TEST_SUITE: phpunit
    - PHP_VERSION: 5.6
      DB_TYPE: oracle
      TEST_SUITE: phpunit

    # PHP 7.0
    - PHP_VERSION: 7.0
      DB_TYPE: sqlite
      TEST_SUITE: phpunit
    #- PHP_VERSION: 7.0
    #  DB_TYPE: mariadb
    #  TEST_SUITE: phpunit
    - PHP_VERSION: 7.0
      DB_TYPE: mysql
      TEST_SUITE: phpunit
    - PHP_VERSION: 7.0
      DB_TYPE: mysqlmb4
      TEST_SUITE: phpunit
    #- PHP_VERSION: 7.0
    #  DB_TYPE: postgres
    #  TEST_SUITE: phpunit
    # - PHP_VERSION: 7.0
    #   DB_TYPE: oracle
    #   TEST_SUITE: phpunit

    # PHP 7.1
    #- PHP_VERSION: 7.1
    #  DB_TYPE: mariadb
    #  TEST_SUITE: phpunit
    #- PHP_VERSION: 7.1
    #  DB_TYPE: mysql
    #  TEST_SUITE: phpunit
    #- PHP_VERSION: 7.1
    #  DB_TYPE: postgres
    #  TEST_SUITE: phpunit
    # - PHP_VERSION: 7.1
    #   DB_TYPE: oracle
    #   TEST_SUITE: phpunit

    # PHP 7.2
    - PHP_VERSION: 7.2
      DB_TYPE: sqlite
      TEST_SUITE: phpunit
    #- PHP_VERSION: 7.2
    #  DB_TYPE: mariadb
    #  TEST_SUITE: phpunit
    #- PHP_VERSION: 7.2
    #  DB_TYPE: mysql
    #  TEST_SUITE: phpunit
    #- PHP_VERSION: 7.2
    #  DB_TYPE: postgres
    #  TEST_SUITE: phpunit
    # - PHP_VERSION: 7.2
    #   DB_TYPE: oracle
    #   TEST_SUITE: phpunit
#
#    # Integration
#    - PHP_VERSION: 7.1
#      DB_TYPE: sqlite
#      TEST_SUITE: integration

    # Code Coverage Computation
    - PHP_VERSION: 7.1
      DB_TYPE: sqlite
      TEST_SUITE: phpunit
      ENABLE_COVERAGE: true

    - PHP_VERSION: 7.1
      DB_TYPE: mariadb
      TEST_SUITE: phpunit
      ENABLE_COVERAGE: true

    - PHP_VERSION: 7.1
      DB_TYPE: sqlite
      TEST_SUITE: phpunit
      FILES_EXTERNAL_TYPE: Owncloud
      ENABLE_COVERAGE: true
